###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?owner=me

###

GET http://localhost:3000/posts/XXX

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "try",
    "owner": "me",
    "content": "blablablablabla"
}

###

DELETE http://localhost:3000/posts/XXX


###

GET http://localhost:3000/comments

###

GET http://localhost:3000/comments?postId=xxx

###

GET http://localhost:3000/comments/xxx

###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "comment": "Hello",
    "owner": "me",
    "postId": "xxx"
}

###

DELETE http://localhost:3000/comments/xxx